[font]
size = 14

[font.bold]
family = "GoMono Nerd Font"

[font.bold_italic]
family = "GoMono Nerd Font"

[font.italic]
family = "GoMono Nerd Font"

[font.normal]
family = "GoMono Nerd Font"

[window]
opacity = 0.95

[window.padding]
x = 15
y = 15

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "alt"

# https://github.com/alacritty/alacritty/issues/1703
[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[shell]
program = "wsl"
args = ["--cd ~", "tmux"]
